### PR TITLE
1.16.3

### PR DESCRIPTION
**Pull request by remplerus**
made it possible to use it in 1.16.3.
- added some PRs to this branch like #202 #189 #154 and some forks too.
- added Netherwood Tree from SilentGear (Thanks to Konicai, even if there's no PR right now)
- added Rainbow Birch Tree from BoP (Thanks to Zaander1151, even if there's no PR right now)

There is just 1 thing i have to mention:
- actually there is a "bug" at showing the percentage at one of the following mods: TOP or WAILA (One does, what it should, the other one doesn't). Maybe if s1 could look at my code to fix that would be fine :)

### CODE REVIEW

**Comment by LiskoSlayer63** [comment]
Built and tested with 1.16.4, doesn't load and instead crashed with multiple "MethodNotFound" exceptions.

**Comment by remplerus** [comment]
well its because you dont have libnonymous i think. every method that is "not found" is in libnonymous, that's why it wont work for you :) (PS it's made for 1.16.3 and not 1.16.4)

**Comment by LiskoSlayer63** [comment]
@remplerus libnonymous was installed (the one inside the "libs" folder, didn't compile it myself). I know it was made for 1.16.3, but I thought it would be good to mention that it will definitely not work on 1.16.4.

Crash report: https://hastebin.com/awalunedop.properties

**Comment by LiskoSlayer63** [comment]
@remplerus Do you have any intentions to fully port this mod to 1.16.x?

**Comment by remplerus** [comment]
probably not. i think this mod is dead

**Comment by RonanNeox** [comment]
This is sad, this mod is really cool and unique and Would also work so well aside with Botany pots !  I loved it in 1.12.2 and was expecting it so much :/

**Comment by BigAl607** [comment]
This mod would be welcomed in 1.16+. I know there are botany pots, but it is incredibly s l o w. This is/was the best way to make compact tree farms in any pack it was in. Would be very nice if it returned.

**Pull request closed without merging**
