### PR TITLE
Tech Reborn's rubber tree

### PR DESCRIPTION
**Pull request by it-is-I-Pants**
I've added the rubber tree from Tech Reborn, please let me know if I've messed something up because I'm still figuring out how to use github. The files work as of Tech Reborn version 2.7.9.301 on Minecraft 1.12.2.

### CODE REVIEW

**Comment by thraaawn** [comment]
Nice, thanks a lot!
Would you mind picking about three of those shapes and remove the others from the pull request? I don't want to have to many shapes per tree.

**Comment by it-is-I-Pants** [comment]
Okay, I got rid of all but 3 of the shapes. Question, is there support for vanilla Mushroom "trees" and if not, would you mind if I added type and shape files for them both?

**Comment by thraaawn** [comment]
Was the tconstruct_purpleslime002.json deletion accidental?

**Comment by it-is-I-Pants** [comment]
Oh shit sorry yeah I hadn't had my coffee yet when I tweaked things for you

**Comment by thraaawn** [comment]
No worries. Please revert commit e473bb5, so the tconstruct file is back.
I can then squash and merge the changes as a single commit.
I also completely forgot to mention: congrats on your first pull request! 🎉

Regarding the mushroom tree. Yes, I had that in mind as well, but would only want to have it grow in a reasonable biome and as such held off on adding it for now. I'll make that a priority of features to add.

**Comment by it-is-I-Pants** [comment]
Okay done. for some reason github just didn't connect to 'git' as in the terminal command for me! So much easier once I'm off the website lol

**Pull request merged**
