### PR TITLE
Removed BoP Ethereal Woods references - Fix for #200, #175 and possibly #184 

### PR DESCRIPTION
**Pull request by NikolaiSchreier**
Also made the project buildable again by adapting TheNut's maven repository address and HWYLA mod version.

### CODE REVIEW

**Comment by shattyyt** [comment]
does this actually not make this mod (bonsai) crash with bop?

**Comment by NikolaiSchreier** [comment]
It definitely fixes #200 for me. 
I have built the version from my forked repository and use it in a modpack on a server I manage. You can try the forked version at https://github.com/NikolaiSchreier/htmtmc/raw/main/minecraft/mods/BonsaiTrees-2.1.2.10-bopfix.jar and see if it fixes any problems you are facing.

**Comment by shattyyt** [comment]
i actually just built from the pull request, should i upgrade?

**Comment by NikolaiSchreier** [comment]
The change is pretty straightforward: I just deleted the two .json files referencing the removed BoP blocks. So pretty certain it won't make anything worse. 
Whether or not it fixes any problem you have - I don't know. Mine was a specific problem that occurred after I upgraded my world to a new BoP version.

**Pull request closed without merging**
